# Generated by Django 5.2 on 2025-04-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('places', '0002_place_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
    ]
