# Generated by Django 5.2 on 2025-04-23 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_place'),
        ('places', '0002_place_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='timezone.now', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
